name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload to Google Drive
        uses: adityassubramanian/gdrive-upload-action@master
        with:
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          filename: "spotify.png"
          folderId: "1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH"
          overwrite: "true"
